### PR TITLE
fix: only sniff a single random node for the node list

### PR DESCRIPTION
**Pull request by mwain**
Instead of sniffing all nodes, it sniffs a single node at a time

### CODE REVIEW

**Comment by atombender** [comment]
So if I understand this correctly, it will try just one random node each time, use its node list, and then exit?

**Comment by mwain** [comment]
> So if I understand this correctly, it will try just one random node each time, use its node list, and then exit?

Yep, as each node has the full cluster state

**Comment by atombender** [comment]
👍 I don't know if there are any edge cases when you're polling a non-master node as opposed to a master; maybe `/_nodes` multiplexes, or it just potentially returns stale state?

You didn't ask for a review yet, but LGTM!

**Comment by mwain** [comment]
Yeah its ready for review :)

**Pull request merged**
